# Generated by Django 3.0.7 on 2021-10-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('desc', models.TextField(max_length=150)),
                ('qnt', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
